openapi: 3.1.0
info:
  title: ACI
  version: 0.0.1-beta.4
paths:
  /v1/apps/{app_name}/functions:
    get:
      tags:
        - apps
      summary: Get App Functions
      description: Get all functions of an application.
      operationId: apps-get_app_functions
      security:
        - APIKeyHeader: []
      parameters:
        - name: app_name
          in: path
          required: true
          schema:
            type: string
            title: App Name
      responses:
        '200':
          description: Successful Response
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/BasicFunctionDefinition'
                title: Response Apps-Get App Functions
        '422':
          description: Validation Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/HTTPValidationError'
components:
  schemas:
    BasicFunctionDefinition:
      properties:
        name:
          type: string
          title: Name
        description:
          type: string
          title: Description
        tags:
          anyOf:
            - items:
                type: string
              type: array
            - type: 'null'
          title: Tags
      type: object
      required:
        - name
        - description
        - tags
      title: BasicFunctionDefinition
      description: |-
        Our own custom function definition, only returns name and description.
        useful for the "search" endpoint, to reduce the amount of data returned.