"""add mcp auth type api key

Revision ID: 4196e57ed0c4
Revises: dac85d66fab6
Create Date: 2025-08-22 18:04:32.625874+00:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '4196e57ed0c4'
down_revision: Union[str, None] = 'dac85d66fab6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Add API_KEY to mcpauthtype enum
    op.execute(
        "ALTER TYPE mcpauthtype ADD VALUE 'API_KEY';"
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
