"""remove embedding

Revision ID: 00fbb93841c7
Revises: d08cfe86e3d2
Create Date: 2025-08-03 10:54:39.894818+00:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '00fbb93841c7'
down_revision: Union[str, None] = 'd08cfe86e3d2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('apps', 'embedding')
    op.drop_column('functions', 'embedding')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('functions', sa.Column('embedding', pgvector.sqlalchemy.vector.VECTOR(dim=1024), autoincrement=False, nullable=False))
    op.add_column('apps', sa.Column('embedding', pgvector.sqlalchemy.vector.VECTOR(dim=1024), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
