"""add execution log api key

Revision ID: db3790220fc0
Revises: a355b9d91b3c
Create Date: 2025-08-22 15:50:55.632135+00:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'db3790220fc0'
down_revision: Union[str, None] = 'a355b9d91b3c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('execution_logs', sa.Column('api_key_name', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('execution_logs', 'api_key_name')
    # ### end Alembic commands ###
