"""add api key name

Revision ID: a355b9d91b3c
Revises: 3e280b2cf0ea
Create Date: 2025-08-22 14:44:48.601453+00:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'a355b9d91b3c'
down_revision: Union[str, None] = '3e280b2cf0ea'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('api_keys', sa.Column('name', sa.String(length=255), nullable=False))
    op.create_unique_constraint('uc_project_api_key_name', 'api_keys', ['project_id', 'name'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uc_project_api_key_name', 'api_keys', type_='unique')
    op.drop_column('api_keys', 'name')
    # ### end Alembic commands ###
