"""simplify project quota

Revision ID: 3e280b2cf0ea
Revises: d651651903b6
Create Date: 2025-08-21 14:08:15.740513+00:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy import func
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '3e280b2cf0ea'
down_revision: Union[str, None] = 'd651651903b6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('projects', sa.Column('monthly_quota_month', sa.Date(), nullable=True))
    op.add_column('projects', sa.Column('monthly_quota_limit', sa.BigInteger(), nullable=False, server_default=sa.text('0')))
    op.add_column('projects', sa.Column('monthly_quota_used', sa.BigInteger(), nullable=False, server_default=sa.text('0')))
    op.alter_column('projects', 'total_quota_used',
               existing_type=sa.INTEGER(),
               type_=sa.BigInteger(),
               existing_nullable=False)
    op.drop_column('projects', 'api_quota_monthly_used')
    op.drop_column('projects', 'api_quota_last_reset')
    op.drop_column('projects', 'daily_quota_used')
    op.drop_column('projects', 'daily_quota_reset_at')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('projects', sa.Column('daily_quota_reset_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=False))
    op.add_column('projects', sa.Column('daily_quota_used', sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('projects', sa.Column('api_quota_last_reset', postgresql.TIMESTAMP(), server_default=sa.text("date_trunc('month'::text, now())"), autoincrement=False, nullable=False))
    op.add_column('projects', sa.Column('api_quota_monthly_used', sa.INTEGER(), server_default=sa.text('0'), autoincrement=False, nullable=False))
    op.alter_column('projects', 'total_quota_used',
               existing_type=sa.BigInteger(),
               type_=sa.INTEGER(),
               existing_nullable=False)
    op.drop_column('projects', 'monthly_quota_used')
    op.drop_column('projects', 'monthly_quota_limit')
    op.drop_column('projects', 'monthly_quota_month')
    # ### end Alembic commands ###
