"""apikey key is just prefix

Revision ID: dac85d66fab6
Revises: db3790220fc0
Create Date: 2025-08-22 17:18:58.867768+00:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'dac85d66fab6'
down_revision: Union[str, None] = 'db3790220fc0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('api_keys', 'key',
               existing_type=postgresql.BYTEA(),
               type_=sa.String(length=255),
               existing_nullable=False)
    op.drop_constraint(op.f('api_keys_encrypted_key_key'), 'api_keys', type_='unique')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(op.f('api_keys_encrypted_key_key'), 'api_keys', ['key'], postgresql_nulls_not_distinct=False)
    op.alter_column('api_keys', 'key',
               existing_type=sa.String(length=255),
               type_=postgresql.BYTEA(),
               existing_nullable=False)
    # ### end Alembic commands ###
