"""remove agent

Revision ID: 7aff29612b03
Revises: 00fbb93841c7
Create Date: 2025-08-03 14:17:50.549370+00:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '7aff29612b03'
down_revision: Union[str, None] = '00fbb93841c7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('api_keys', sa.Column('project_id', sa.UUID(), nullable=False))
    op.drop_constraint(op.f('api_keys_agent_id_key'), 'api_keys', type_='unique')
    op.drop_constraint(op.f('api_keys_agent_id_fkey'), 'api_keys', type_='foreignkey')
    op.create_foreign_key(None, 'api_keys', 'projects', ['project_id'], ['id'])
    op.drop_column('api_keys', 'agent_id')
    op.drop_table('agents')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('api_keys', sa.Column('agent_id', sa.UUID(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'api_keys', type_='foreignkey')
    op.create_foreign_key(op.f('api_keys_agent_id_fkey'), 'api_keys', 'agents', ['agent_id'], ['id'])
    op.create_unique_constraint(op.f('api_keys_agent_id_key'), 'api_keys', ['agent_id'], postgresql_nulls_not_distinct=False)
    op.drop_column('api_keys', 'project_id')
    op.create_table('agents',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('project_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('name', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('description', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('custom_instructions', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=False),
    sa.Column('allowed_apps', postgresql.ARRAY(sa.VARCHAR(length=255)), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], name=op.f('agents_project_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('agents_pkey'))
    )
    # ### end Alembic commands ###
