"""add org id to app and function

Revision ID: 52a4f951efa7
Revises: 7aff29612b03
Create Date: 2025-08-08 13:58:05.011853+00:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '52a4f951efa7'
down_revision: Union[str, None] = '7aff29612b03'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('apps', sa.Column('org_id', sa.UUID(), nullable=True))
    op.drop_constraint(op.f('apps_name_key'), 'apps', type_='unique')
    op.create_index(op.f('ix_apps_name'), 'apps', ['name'], unique=False)
    op.create_index(op.f('ix_apps_org_id'), 'apps', ['org_id'], unique=False)
    op.create_index('uq_app_orgid_name', 'apps', [sa.literal_column("coalesce(CAST(org_id AS VARCHAR), 'null_org')"), 'name'], unique=True, postgresql_using='btree')
    op.add_column('functions', sa.Column('org_id', sa.UUID(), nullable=True))
    op.drop_constraint(op.f('functions_name_key'), 'functions', type_='unique')
    op.create_index(op.f('ix_functions_name'), 'functions', ['name'], unique=False)
    op.create_index(op.f('ix_functions_org_id'), 'functions', ['org_id'], unique=False)
    op.create_index('uq_function_orgid_name', 'functions', [sa.literal_column("coalesce(CAST(org_id AS VARCHAR), 'null_org')"), 'name'], unique=True, postgresql_using='btree')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('uq_function_orgid_name', table_name='functions', postgresql_using='btree')
    op.drop_index(op.f('ix_functions_org_id'), table_name='functions')
    op.drop_index(op.f('ix_functions_name'), table_name='functions')
    op.create_unique_constraint(op.f('functions_name_key'), 'functions', ['name'], postgresql_nulls_not_distinct=False)
    op.drop_column('functions', 'org_id')
    op.drop_index('uq_app_orgid_name', table_name='apps', postgresql_using='btree')
    op.drop_index(op.f('ix_apps_org_id'), table_name='apps')
    op.drop_index(op.f('ix_apps_name'), table_name='apps')
    op.create_unique_constraint(op.f('apps_name_key'), 'apps', ['name'], postgresql_nulls_not_distinct=False)
    op.drop_column('apps', 'org_id')
    # ### end Alembic commands ###
