"""add mcp servers

Revision ID: d08cfe86e3d2
Revises: 20c2c62a7295
Create Date: 2025-08-02 17:47:54.054903+00:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'd08cfe86e3d2'
down_revision: Union[str, None] = '20c2c62a7295'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('mcp_servers',
    sa.Column('id', sa.String(length=255), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('app_config_id', sa.UUID(), nullable=False),
    sa.Column('auth_type', sa.Enum('SECRET_LINK', 'OAUTH2', name='mcpauthtype'), nullable=False),
    sa.Column('allowed_tools', postgresql.ARRAY(sa.String(length=255)), nullable=False),
    sa.Column('mcp_link', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('last_used_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['app_config_id'], ['app_configurations.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('app_config_id', 'name', name='uc_app_config_mcp_server_name')
    )
    op.create_index(op.f('ix_mcp_servers_mcp_link'), 'mcp_servers', ['mcp_link'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_mcp_servers_mcp_link'), table_name='mcp_servers')
    op.drop_table('mcp_servers')
    # ### end Alembic commands ###
